import type { BidLedger, CompileRequest } from "./types";

export const sampleCompileRequest: CompileRequest = {
  rfqId: "RFQ-2027-014",
  rfqLines: [
    {
      id: "PKG-001",
      description: "5-ply BC flute corrugated box, 18 BF",
      quantity: 12000,
      uom: "kg",
      attributes: { ply: 5, burstFactor: 18, destination: "Pune Zone 2" },
      mandatory: true,
    },
    {
      id: "PKG-002",
      description: "3-ply B flute corrugated box, 16 BF",
      quantity: 10000,
      uom: "kg",
      attributes: { ply: 3, burstFactor: 16, destination: "Pune Zone 2" },
      mandatory: true,
    },
    {
      id: "PKG-003",
      description: "5-ply heavy-duty corrugated box, 22 BF",
      quantity: 10000,
      uom: "kg",
      attributes: { ply: 5, burstFactor: 22, destination: "Pune Zone 2" },
      mandatory: true,
    },
  ],
  vendors: [
    { id: "packright", name: "PackRight" },
    { id: "boxco", name: "BoxCo" },
    { id: "corrpro", name: "CorrPro" },
  ],
  artifacts: [
    {
      id: "artifact-packright-email",
      vendorId: "packright",
      fileName: "packright-response.eml",
      mimeType: "message/rfc822",
      text: "₹42/kg for the 5-ply, ₹38/kg for the 3-ply, rest same as last year. Freight extra at actuals. Delivery 10 days.",
      version: 1,
    },
    {
      id: "artifact-boxco-sheet",
      vendorId: "boxco",
      fileName: "boxco-commercial.csv",
      mimeType: "text/csv",
      text: "Item,Rate,UOM,Freight,Lead time\nPKG-001,41.90,kg,Included,7 days\nPKG-002,37.80,kg,Included,7 days\nPKG-003,43.25,kg,Included,7 days",
      version: 1,
    },
    {
      id: "artifact-corrpro-note",
      vendorId: "corrpro",
      fileName: "corrpro-rate-card.txt",
      mimeType: "text/plain",
      text: "PKG-001 INR 42.60/kg; PKG-002 INR 39/kg; PKG-003 INR 44/kg. Freight included. Delivery within 5 days. Net 30 days from receipt.",
      version: 2,
    },
  ],
};

export const sampleLedger: BidLedger = {
  id: "BL-RFQ-2027-014",
  rfqId: sampleCompileRequest.rfqId,
  version: 3,
  asOf: "2026-08-29T18:38:15Z",
  rfqLines: sampleCompileRequest.rfqLines,
  claims: [
    {
      id: "claim-packright-freight",
      vendorId: "packright",
      kind: "freight",
      rawValue: "Freight extra at actuals",
      interpretedValue: "excluded_unknown",
      conditions: [],
      source: {
        artifactId: "artifact-packright-email",
        fileName: "packright-response.eml",
        quote: "Freight extra at actuals.",
      },
      confidence: { extraction: 0.99, mapping: 1, normalization: 1 },
      status: "validated",
    },
    {
      id: "claim-boxco-freight",
      vendorId: "boxco",
      kind: "freight",
      rawValue: "Included",
      interpretedValue: true,
      conditions: [],
      source: {
        artifactId: "artifact-boxco-sheet",
        fileName: "boxco-commercial.csv",
        sheet: "Commercial",
        row: 2,
        quote: "Freight: Included",
      },
      confidence: { extraction: 1, mapping: 1, normalization: 1 },
      status: "system_verified",
    },
  ],
  bids: [
    {
      vendorId: "packright",
      vendorName: "PackRight",
      offers: sampleCompileRequest.rfqLines.map((line, index) => ({
        rfqLineId: line.id,
        vendorId: "packright",
        claimIds: [],
        quotedUnitPrice: [252.5, 238.2, 279.1][index],
        normalizedUnitPrice: [252.5, 238.2, 279.1][index],
        currency: "INR",
        uom: "kg",
        lineTotal: [3030000, 2382000, 2791000][index],
        matchConfidence: 0.94,
        status: "validated",
      })),
      freight: { type: "excluded_unknown" },
      leadTimeDays: 10,
      paymentTerms: "Net 30",
      technicalCompliance: true,
    },
    {
      vendorId: "boxco",
      vendorName: "BoxCo",
      offers: sampleCompileRequest.rfqLines.map((line, index) => ({
        rfqLineId: line.id,
        vendorId: "boxco",
        claimIds: [],
        quotedUnitPrice: [255, 241, 280][index],
        normalizedUnitPrice: [255, 241, 280][index],
        currency: "INR",
        uom: "kg",
        lineTotal: [3060000, 2410000, 2800000][index],
        matchConfidence: 1,
        status: "system_verified",
      })),
      freight: { type: "included", amount: 0 },
      leadTimeDays: 7,
      paymentTerms: "Net 30 from invoice",
      technicalCompliance: true,
    },
    {
      vendorId: "corrpro",
      vendorName: "CorrPro",
      offers: sampleCompileRequest.rfqLines.map((line, index) => ({
        rfqLineId: line.id,
        vendorId: "corrpro",
        claimIds: [],
        quotedUnitPrice: [265, 250, 294][index],
        normalizedUnitPrice: [265, 250, 294][index],
        currency: "INR",
        uom: "kg",
        lineTotal: [3180000, 2500000, 2940000][index],
        matchConfidence: 0.97,
        status: "system_verified",
      })),
      freight: { type: "included", amount: 0 },
      leadTimeDays: 5,
      paymentTerms: "Net 30 from receipt",
      technicalCompliance: true,
    },
  ],
  events: [
    {
      id: "event-1",
      at: "2026-08-29T18:38:12Z",
      actor: "ai",
      action: "commercial_claim_extracted",
      entityId: "claim-packright-freight",
      model: "gemini-2.5-pro",
    },
    {
      id: "event-2",
      at: "2026-08-29T18:38:15Z",
      actor: "system",
      action: "decision_impact_detected",
      entityId: "claim-packright-freight",
      reason: "Unknown freight can change supplier ranking.",
    },
  ],
};
